version: '3.9'

services:
  traffic_db:
    container_name: PostgreSQL
    restart: always
    image: postgres
    ports:
      - "127.0.0.1:15432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_traffic:/var/lib/postgresql/data
      - ./resources/db/migration/backup-1.1.sql:/docker-entrypoint-initdb.d/traffic_backup.sql

  app:
    restart: always
    build: ..
    ports:
      - "8000:8000"
    depends_on: 
      - traffic_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://traffic_db:5432/${POSTGRES_DB}'
      JAVA_OPTS: '-Xmx512m'

  # pgadmin4:
  #   container_name: pgAdmin4
  #   restart: always
  #   image: dpage/pgadmin4:latest
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - postgresql

  # apache:
  #   container_name: Apache
  #   image: httpd:latest
  #   ports:
  #     - 8073:80
  #   volumes:
  #     - apache-data:/usr/local/apache2/htdocs
  #   depends_on:
  #     - postgresql

volumes:
  pg_traffic:
  # pgadmin-data:
  # apache-data: